# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # ==========================
        # TABEL SISWA
        # ==========================
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),

        # ==========================
        # TABEL BUKU
        # ==========================
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100, blank=True, null=True)),
                ('penerbit', models.CharField(max_length=255, blank=True, null=True)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('rak', models.CharField(max_length=50, blank=True, null=True)),
                ('stok', models.IntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buku',
            },
        ),

        # ==========================
        # TABEL PEMINJAMAN
        # ==========================
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(
                    max_length=50,
                    blank=True,
                    null=True
                )),
                ('petugas', models.CharField(
                    max_length=255,
                    blank=True,
                    null=True
                )),
                (
                    'buku',
                    models.ForeignKey(
                        db_column='buku_id',
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='perpus.buku',
                    ),
                ),
                (
                    'siswa',
                    models.ForeignKey(
                        db_column='siswa_id',
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='perpus.siswa',
                    ),
                ),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
    ]